config/routes.rb
Rails.application.routes.draw do
  resources :engineers
  resources :people
  get 'pages/about'
  get 'pages/contact'
  root 'people#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "no.jpeg"
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :jobtitle, :industry, :company, :location, :contact, :linkedin, :other, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rankedin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/yourcode.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/9cf169900f.js" crossorigin="anonymous"></script>

    <!-- Optional theme -->
     <style>
     section {
    padding: 60px 0;
}

section .section-title {
    text-align: center;
    color: #007b5e;
    margin-bottom: 50px;
    text-transform: uppercase;
}
#footer {
    background: #007b5e !important;
}
#footer h5{
	padding-left: 10px;
    border-left: 3px solid #eeeeee;
    padding-bottom: 6px;
    margin-bottom: 20px;
    color:#ffffff;
}
#footer a {
    color: #ffffff;
    text-decoration: none !important;
    background-color: transparent;
    -webkit-text-decoration-skip: objects;
}
#footer ul.social li{
	padding: 3px 0;
}
#footer ul.social li a i {
    margin-right: 5px;
	font-size:25px;
	-webkit-transition: .5s all ease;
	-moz-transition: .5s all ease;
	transition: .5s all ease;
}
#footer ul.social li:hover a i {
	font-size:30px;
	margin-top:-10px;
}
#footer ul.social li a,
#footer ul.quick-links li a{
	color:#ffffff;
}
#footer ul.social li a:hover{
	color:#eeeeee;
}
#footer ul.quick-links li{
	padding: 3px 0;
	-webkit-transition: .5s all ease;
	-moz-transition: .5s all ease;
	transition: .5s all ease;
}
#footer ul.quick-links li:hover{
	padding: 3px 0;
	margin-left:5px;
	font-weight:700;
}
#footer ul.quick-links li a i{
	margin-right: 5px;
}
#footer ul.quick-links li:hover a i {
    font-weight: 700;
}

@media (max-width:767px){
	#footer h5 {
    padding-left: 0;
    border-left: transparent;
    padding-bottom: 0px;
    margin-bottom: 10px;
}
}
     .navbar .navbar-brand {
      margin-bottom:0; 
       margin:0;
      padding: 0;
     }
     .logo {
       width: 200px;
     }
     section {
    padding: 50px 0;
}



}

.b

     
     </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  

    <link rel="shortcut icon" href="fzv.png" />

    </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top navbar-static-top">
  <a class="navbar-brand" href="/"><%= image_tag "rankgin.png", class: "logo"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;&emsp;

  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
        
&emsp;
&emsp;
&emsp;
&emsp;
&emsp;
&emsp;
&emsp;
&emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;

&emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;&emsp;

  &emsp;
  &emsp;
  &emsp;
  &emsp;
  &emsp;
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class="nav-link" href="/pages/about">Login<span class="sr-only">(current)</span></a>
      </li>
      &nbsp
      <li class="nav-item">
        <a class="nav-link" href="/pages/contact">Signup</a>
      </li>
     </ul>

     </ul>
    
     
  </div>
</nav>
<% unless controller_name == "pages"  %>

<div class="jumbotron card card-image" style="background-image: url(https://mdbootstrap.com/img/Photos/Others/gradient1.jpg);">
  <div class="text-white text-center py-5 px-4">
    <div>
      <h2 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Welcome to rankedin</strong></h2>
      <p class="mx-5 mb-5">Ratings and reviews are huge part of our decision making proccess, we rate our doctors, lawyers, and buisiness establishments. Why don't we apply the same prinicples to the people in the tech community: the engineers, analysts, product managers, and even c-suite execs?
     
      </p>
      <a class="btn btn-outline-white btn-md"><i class="fas fa-clone left"></i> Think yelp but for engineers and analysts!</a>
    </div>
  </div>
</div>
<% end %>

<div class="container">
    <%= yield %>
    
  

</div>



    
</body>  

<section id="footer">
<div class="container">
  <div class="row text-center text-xs-center text-sm-left text-md-left">
    <div class="col-xs-12 col-sm-4 col-md-4">
      <h5>Quick links</h5>
      <ul class="list-unstyled quick-links">
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
      </ul>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
      <h5>Quick links</h5>
      <ul class="list-unstyled quick-links">
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Videos</a></li>
      </ul>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
      <h5>Quick links</h5>
      <ul class="list-unstyled quick-links">
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Home</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>About</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>FAQ</a></li>
        <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Get Started</a></li>
        <li><a href="https://wwwe.sunlimetech.com" title="Design and developed by"><i class="fa fa-angle-double-right"></i>Imprint</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
      <ul class="list-unstyled list-inline social text-center">
        <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
        <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
        <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
        <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
        <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
      </ul>
    </div>
    </hr>
  </div>	
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
      <p><u><a href="https://www.nationaltransaction.com/">National Transaction Corporation</a></u> is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
      <p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
    </div>
    </hr>
  </div>	
</div>
</section>
<!-- ./Footer -->


    
    


  
  


  
</html>

app/views/pages/about.html.erb
<h1>What is Rankedin?</h1>
<h3>Ratings and reviews are huge part of our decision making proccess, we rate our doctors, lawyers, and buisiness establishments. Why
 don't we apply the same prinicples to the people in the tech community: the engineers, 
 analysts, product managers, and even c-suite execs? Meet 
 Rankedin an online platform where you  potetnials employers and current peers can view the rating and reviews of any working employeein the tech or buisneess comunnity. Think yelp but for engineers and analysts!</h3>

app/views/pages/contact.html.erb
<h1>We would love to get feeback from you, as we are still in beta</h1>
<p>Submit the form below to gives us feedback on how we can improve</p>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true, html: { multipart: true }) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :jobtitle %>
    <%= form.text_field :jobtitle, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :industry %>
    <%= form.text_field :industry, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :contact %>
    <%= form.text_field :contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :other %>
    <%= form.text_field :other, class: "form-control" %>
  </div>

  <div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: "form-control" %>
</div>

  <div class="form-group">
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
<% @people.each do |person| %>
  <div class="col-md-3">


  <div class="card" style="width: 22.5rem;">
  <%= image_tag person.image.url(:medium) %>
  <div class="card-body">
 <h4 class="card-title"> <center><%= person.name %> <i class="fas fa-check-circle" style="color:#19F9A2"></i></center></h4><h5><center><%= person.jobtitle %></center></h5>
 <h5><center>@<%= person.company %></center></h5>
    <hr>
  <center>  <i class="fas fa-map-marker-alt"></i> <%= person.location %><br> <c/center>
    
    
  
   <br>
  <center> <font color="red">  <div class="btn btn-success"> 
  <%= link_to 'Show', person %> </div>  </font> </center>
  </div>

        <div>
  

     </div>
  </div>
</div>

  <%end%>  
</div>






<h1>People</h1>

<table class="table">
  <thead>
    <tr>
    <th>Profile Picture</th>
      <th>Name</th>
      <th>Job Title</th>
      <th>Company</th>
      <th>Micro-Bio</th>
      <th>Location</th>
      <th>Contact</th>
      <th>Linkedin</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= image_tag person.image.url(:thumb) %></td>

        <td><%= person.name %></td>
        <td><%= person.jobtitle %></td>
        <td><%= person.company %></td>
        <td><%= person.industry %></td>
        <td><%= person.location %></td>
        <td><%= person.contact %></td>
        <td style ="word-break:break-all;"><%= link_to person.linkedin %></td>
        <td style ="word-break:break-all;"><%= link_to person.other %></td>
       
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<br>
<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<head>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>



</head>
<style>
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
</style>



<p id="notice"><%= notice %></p>







<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                        <%= image_tag @person.image.url(:medium) %>

                           
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h1>
                                    <%= @person.name %>
                                    </h1>
                                    <h3>
                                    <%= @person.jobtitle %> at <%= @person.company %>
                                    </h3>
                                    <h4> Average Rating: <span>8/10</span></h4>

                                    <h4> Summary: </h4>
                                    <p><%= @person.industry %></p>
                                    
                                   
                               </div>
                               
                           </div>
                        
                    <div class="col-md-2">
                    

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>INFORMATION</p>
                            <%= @person.location %> <br>
                            <%= @person.contact %><br>
                            <%= @person.linkedin %> <br>
                            <%= @person.other %>

                            <br>
                            <p>LOCATION</p>
                            <div id="map-container-google-1" class="z-depth-1-half map-container" style="width: 100px">
                            <iframe src="https://maps.google.com/maps?q=manhatan&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
                              style="border:0" allowfullscreen></iframe>
                          </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        
                           
                   
                    <h4> Rankings: </h4>
                    <div class="card">
                    
                    <div class="card-body">
                      <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                      </blockquote>
                    </div>
                  </div>
                                        
                            
                        
                                   
                             
                            </div>
                        </div>
                    </div>
                    
                </div>
             
            </form>  
            
            
        </div>

                                    
      


<%= link_to 'Edit', edit_person_path(@person) %> 
|

<%= link_to 'Back', "/" %>